#!/bin/bash
# This would create a development virtual environment
# - uses requirements.txt
# - install repository itself in development mode.
set -x

echo "Creating python virtual environment."

SCRIPTPATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
SRC_ROOT="$SCRIPTPATH/.."

# force using pytest from venv - otherwise it uses system packages
sudo pip3 uninstall pytest

cd ${SRC_ROOT}
rm -r venv
python3 -m venv --system-site-packages venv

venv_pip=${SRC_ROOT}/venv/bin/pip

$venv_pip install -v -r $SRC_ROOT/requirements.txt

# install repository
$venv_pip install -v -e .

bash ./docker/install_custom_tinyda.sh venv/ tinyDA/